#Code generated from a CineditorML model
from moviepy.editor import *
from moviepy.video import *
backgroundintroClip= ColorClip(size=(1920,1080), color=(0, 0, 0)).set_duration(10)
textintroClip = TextClip(txt="INTRO TITLE",fontsize=70,color='white').set_position("center").set_duration(3)
introClip = CompositeVideoClip([backgroundintroClip,textintroClip])
temporisedintroClip = TextClip(txt=" ",fontsize=70,color='white').set_duration(4)
transparentColorClipintroClip= ColorClip(size=(1920,1080), color=(0, 0, 0)).set_opacity(0.0).set_duration(7)
concatenatedintroClip = concatenate_videoclips([temporisedintroClip,textintroClip]).set_position("center")
transparentintroClip = CompositeVideoClip([transparentColorClipintroClip,concatenatedintroClip])
introClip = CompositeVideoClip([backgroundintroClip,transparentintroClip])
clip1 = VideoFileClip("resources/video/alderamin 1.webm")
clip1a = clip1.subclip(1,15)
textclip1a_with_subtitle = TextClip(txt="SUBCLIP 1A SUBTITLE",fontsize=70,color='white').set_position("bottom").set_duration(5)
temporisedclip1a_with_subtitle = TextClip(txt=" ",fontsize=70,color='white').set_duration(7)
transparentColorClipclip1a_with_subtitle= ColorClip(size=(1920,1080), color=(0, 0, 0)).set_opacity(0.0).set_duration(12)
concatenatedclip1a_with_subtitle = concatenate_videoclips([temporisedclip1a_with_subtitle,textclip1a_with_subtitle]).set_position("bottom")
transparentclip1a_with_subtitle = CompositeVideoClip([transparentColorClipclip1a_with_subtitle,concatenatedclip1a_with_subtitle])
clip1a_with_subtitle = CompositeVideoClip([clip1a,concatenatedclip1a_with_subtitle])
s2 = TextClip(txt="SUBCLIP 30 SECS AFTER S1",fontsize=70,color='white').set_duration(10).set_position("left")
clip1b = clip1.subclip(5,7)
s3 = TextClip(txt="SUBCLIP 1B SUBTITLE",fontsize=70,color='white').set_duration(15).set_position("right")
clip1b = CompositeVideoClip([clip1b,s3])
backgroundoutroClip= ColorClip(size=(1920,1080), color=(0, 0, 0)).set_duration(10)
textoutroClip = TextClip(txt="THANKS FOR WATCHING",fontsize=70,color='white').set_position("center").set_duration(8)
outroClip = CompositeVideoClip([backgroundoutroClip,textoutroClip])
temporisedoutroClip = TextClip(txt=" ",fontsize=70,color='white').set_duration(1)
transparentColorClipoutroClip= ColorClip(size=(1920,1080), color=(0, 0, 0)).set_opacity(0.0).set_duration(9)
concatenatedoutroClip = concatenate_videoclips([temporisedoutroClip,textoutroClip]).set_position("center")
transparentoutroClip = CompositeVideoClip([transparentColorClipoutroClip,concatenatedoutroClip])
outroClip = CompositeVideoClip([backgroundoutroClip,transparentoutroClip])
result = concatenate_videoclips([introClip,clip1a,clip1b,outroClip])
result.write_videofile("resources/result_videos/scenario2.webm",fps=25)
